### ISSUE TITLE
Fix Issues

### ISSUE THREAD

**Issue by saadparwaiz1** [GideonWolfe/nvim-lua#1]
- Autocomplete: add `shortmess+=c` in your config or with lua it'll be `vim.opt.shortmess:append('c')`
- Border For PopUp Menu: bit of a hack but you can define the pmenu highlight with a underline which should give it border effect
- lspinstall: use a package manager.
- nvimtree: set the following variable `let g:nvim_tree_auto_open = 1`

**Comment by GideonWolfe** [comment]
Bless your heart!!

**Comment by GideonWolfe** [comment]
@saadparwaiz1 Hmm, I can't seem to get the auto open variable for nvimtree to work. Just opening a directory gives me an empty buffer.
